Ak customer controller
NSS-Likeable-Lemurs/BangazonAPI pull request #18
Opened 2018-10-30 20:49 UTC by Akeen11

## Link to Ticket
Closes #2 

## Description of Proposed Changes
- Created model for Customer
- Created mvc for Customer

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout <AK-CustomerController>
Add filler Customer data into your SQL
Go to Bangazon.sql folder, copy and paste initial data into database for testing
Test POST, PUT, DELETE, and GET in POSTMAN
```

## Impacted Areas in Application

List general components of the application that this PR will affect:

* CustomerModel and CustomerModelController

## Mentions @username

@davidnicholastaylor 
@KaylaReid 
@askingalot 

## Definition of Done

1. The project must be fully documented. This includes the following:
    1. Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.
    1. Every class must be documented with purpose, author, and methods.
    1. Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.
1. The project must be able to run fully, and without errors, on each teammate's system.
1. Fulfills every requirement.
Every line of code has been peer reviewed.
1. For projects that require unit testing, core functionality must be identified and have at least one test for each.

2018-10-30 20:55 UTC, KaylaReid approved these changes
looks great

2018-10-30 20:55 UTC, davidnicholastaylor approved these changes
Looks great

2018-10-30 21:27 UTC, askingalot requested changes
I'd say this is 95% there. It's good work, but just needs one or two more things. See my other comments.

2018-10-30 21:27 UTC, askingalot commented on Bangazon/Controllers/CustomersController.cs
> +            Console.WriteLine(sql);
This was great for debugging, but itsn't needed now.

2018-10-30 21:27 UTC, askingalot commented on Bangazon/Controllers/CustomersController.cs
> +    public class CustomersController : Controller
Your controller should inherit from `ControllerBase`

2018-10-30 21:27 UTC, askingalot commented on Bangazon/Controllers/CustomersController.cs
> +        public async Task<IActionResult> Get(string q, string _include)
What does this method do if I pass both a `q` and and `_include` parameter?

For example, what happens if I use a URL such as http://localhost:5000/api/Customer?q=bob&_include=payments

2018-10-31 00:41 UTC, askingalot requested changes

2018-10-31 00:41 UTC, askingalot commented on Bangazon/Controllers/CustomersController.cs
> +            if (_include == "products")
When _include=products is specified and a customer has not created any products, that customer is not being returned. I would expect to see the customer with an empty list of products.

2018-10-31 18:10 UTC, askingalot approved these changes

2018-10-31 18:11 UTC, merged